zenrocklabs/zrchain

- CONTRIBUTING.md
- README.md
This PR adds two files `README.md` and `CONTRIBUTING.md`.
> chore: add readme & contribution

- sidecar/config.yaml
- sidecar/main.go
- sidecar/neutrino/build.go
- sidecar/proxy_test.go
- sidecar/types.go
add neutrino database path to sidecar config
> fix: add neutrino database config path 

- x/validation/keeper/alias_functions.go
- x/validation/keeper/val_state_change.go
AVS rewards were not correctly calculated - this PR addresses the issue.
The rewards code has also been refactored for legibility and maintainability.
> fix: avs rewards calculation + refactor

- x/mint/abci.go
- x/mint/keeper/keeper.go
This PR gives the excess/surplus distribution its own function. This removes complexity. Added temporary logs.
> refactor: excess distribution

- app/app.go
This PR lets the `mint` module receive funds and adds upgrade files
> feat: mint recv permission

- app/upgrades.go
- app/upgrades/v5beta3/constants.go
- app/upgrades/v5beta3/upgrade.go
This PR adds rudimentary upgrade files to the branch. Module upgrades are still missing
> add upgrade shell

- x/validation/keeper/migrations.go
- x/validation/migrations/v6/store.go
- x/validation/module/module.go
This PR adds module upgrade files for the `x/validation` v6 module.
> chore: validation v6 upgrade files

- sidecar/oracle.go
https://app.clickup.com/t/86b3ayfue
> ethereum gas estimation

- go-client/tx_raw_client.go
- go-client/tx_zenbtc.go
Increase Max Fees for ZenBTC Proof/Redemption transactions
> fix: increase fees for ZenBTC transactions

- app/app.go
This PR wires the zentp module to `app.go`
> feat: wire zentp in app.go

- go.mod
- go.sum
validate that redemption inputs are coming from zenbtc wallets
> fix: add zenbtc redemption input validation

- go-client/query_client.go
remove check grpc cert in service.crt file and replace with SkipVerify
> fix: remove file-based validation of  grpc cert

- go-client/query_client.go
fix: verify server against the system root pool
> fix: use system root pool to verify grpc server connection

- go.mod
- go.sum
- shared/zenbtc_keeper_interface.go
- sidecar/main.go
- sidecar/oracle.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
- [feat: optimise store walks by starting from first pending elem in zenbtc VE flow](https://github.com/zenrocklabs/zrchain/pull/170/commits/e1babe1bfd50720a69bd6741e1881a9abc439637)
- [feat: use ntp for time sync on sidecar](https://github.com/zenrocklabs/zrchain/pull/170/commits/a823418907e79b3c2807d02a9a52db8e74e5a414)
- [feat: pararellise sidecar requests in fetchAndProcessState](https://github.com/zenrocklabs/zrchain/pull/170/commits/1b3adc95049cc9cca5a401de6c07bb58ab02a957)
> feat: polish pass

- go-client/query_client.go
I'm hoping this will fix Intermittent connection drops with the bitcoin-proxy
> fix: add keepalive to Client Connection

- policy/policy.go
- x/identity/keeper/msg_server_add_workspace_owner.go
- x/identity/keeper/msg_server_append_child_workspace.go
- x/identity/keeper/msg_server_new_child_workspace.go
- x/identity/keeper/msg_server_remove_workspace_owner.go
- x/identity/keeper/msg_server_update_workspace.go
- x/policy/keeper/actions.go
- x/policy/keeper/actions_test.go
- x/policy/keeper/msg_server_approve_action_test.go
- x/treasury/keeper/msg_server_new_ica_transaction_request.go
- x/treasury/keeper/msg_server_new_key_request.go
- x/treasury/keeper/msg_server_new_key_request_test.go
- x/treasury/keeper/msg_server_new_sign_transaction_request.go
- x/treasury/keeper/msg_server_new_signature_request.go
- x/treasury/keeper/msg_server_update_key_policy.go
This PR extends the set of action creators to workspace owners that are not part of the policy. This empowers workspace owners while it sharpens the responsibility of policy participants.
> feat: add action extension

- go.mod
- go.sum
feat: trigger v6 release (BREAKING CHANGE)
> feat: trigger v6 release (BREAKING CHANGE)

- app/upgrades.go
- app/upgrades/v6/constants.go
- app/upgrades/v6/upgrade.go
This PR adds upgrade files for the zrchain `v6` upgrade.
> fix: v6 upgrade

- sidecar/oracle.go
- x/validation/keeper/abci.go
- x/validation/types/expected_keepers.go
- x/zentp/keeper/keeper.go
- x/zentp/keeper/msg_server_bridge.go
This PR adds fixes for the bridging fee process
> fix: bridging fee

- sidecar/shared/types.go
Update zenBTC addresses for testnet
> feat: testnet zenbtc sol params

- x/validation/keeper/abci.go
- x/zentp/module/autocli.go
This PR fixes the correct registering of solana mint events and fixes the autocli for the authadminkey.
> fix: solana events
